# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types: [ scss ]

  - repo: https://github.com/PyCQA/isort/
    rev: "5.12.0"
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/autoflake/
    rev: "v2.2.0"
    hooks:
      - id: autoflake
        args:
          - "--in-place"
          - "--expand-star-imports"
          - "--remove-all-unused-imports"
          - "--ignore-init-module-imports"
  - repo: https://github.com/psf/black
    rev: "23.3.0"
    hooks:
      - id: black
        args: [ --line-length=79 ]
  - repo: https://github.com/PyCQA/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8
        exclude: migrations/
