# Generated by Django 4.0.4 on 2022-07-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(default='sample.pdf', max_length=1000),
            preserve_default=False,
        ),
    ]
