# Generated by Django 4.0.4 on 2022-07-12 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0002_file_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assettype',
            name='suggested_field',
        ),
        migrations.AddField(
            model_name='suggestedfield',
            name='asset_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='filemanager.assettype'),
            preserve_default=False,
        ),
    ]
