# Generated by Django 4.0.4 on 2022-07-14 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0004_suggestedfield_has_camera_access_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filemanager.assettype')),
            ],
        ),
    ]
