# Generated by Django 4.0.4 on 2022-07-14 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0005_suggestedfolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestedfolder',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_folder', to='filemanager.assettype'),
        ),
    ]
