# Generated by Django 4.0.4 on 2022-07-15 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0007_alter_suggestedfield_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='asset_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='filemanager.assettype'),
        ),
    ]
