# Generated by Django 4.0.4 on 2022-08-23 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filemanager', '0009_alter_folder_asset_type'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='StickyNote',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created', models.DateTimeField(auto_now_add=True)),
        #         ('updated', models.DateTimeField(auto_now=True)),
        #         ('title', models.CharField(max_length=100)),
        #         ('discription', models.CharField(max_length=500)),
        #         ('pin', models.BooleanField(default=False)),
        #         ('color', models.CharField(max_length=10)),
        #         ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #         ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickynotes', to='filemanager.folder')),
        #     ],
        # ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[(1, 'FILE_ADD'), (2, 'FILE_EDIT'), (3, 'FILE_DELETE'), (4, 'FOLDER_ADD'), (5, 'FOLDER_EDIT'), (6, 'FOLDER_DELETE'), (7, 'COMMENT_ADD'), (8, 'COMMENT_EDIT'), (9, 'COMMENT_DELETE')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='foldercomment',
            name='comment_ptr',
        ),
        migrations.RemoveField(
            model_name='foldercomment',
            name='folder',
        ),
        migrations.DeleteModel(
            name='FileComment',
        ),
        migrations.DeleteModel(
            name='FolderComment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='file',    
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filemanager.file'),
        ),
        migrations.AddField(
            model_name='comment',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filemanager.folder'),
        ),
        # migrations.AddField(
        #     model_name='file',
        #     name='thumbnail',
        #     field=models.ImageField(null=True, upload_to='thumbnails'),
        # ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_activity', to='filemanager.comment'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_activty', to='filemanager.file'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_activity', to='filemanager.folder'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
