# Generated by Django 4.0.4 on 2022-08-25 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filemanager', '0010_stickynote_useractivity_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='file',
        #     name='thumbnail',
        #     field=models.ImageField(null=True, upload_to='thumbnails'),
        # ),
        # migrations.CreateModel(
        #     name='StickyNote',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created', models.DateTimeField(auto_now_add=True)),
        #         ('updated', models.DateTimeField(auto_now=True)),
        #         ('title', models.CharField(max_length=100)),
        #         ('discription', models.CharField(max_length=500)),
        #         ('pin', models.BooleanField(default=False)),
        #         ('color', models.CharField(max_length=10)),
        #         ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #         ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickynotes', to='filemanager.folder')),
        #     ],
        # ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('permission', models.CharField(choices=[(1, 'CO-OWNER'), (2, 'CONTRIBUTER'), (3, 'VIEW ONLY')], max_length=100)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filemanager.folder')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]

