# Generated by Django 4.0.4 on 2022-08-29 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filemanager', '0011_file_thumbnail_stickynote_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails'),
        ),
        migrations.AddField(
            model_name='share',
            name='receiver_email',
            field=models.EmailField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='share',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with', to='filemanager.folder'),
        ),
        migrations.AlterField(
            model_name='share',
            name='receiver',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StickyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=500)),
                ('pin', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickynotes', to='filemanager.folder')),
            ],
        ),
    ]
