# Generated by Django 4.0.4 on 2022-08-29 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filemanager', '0012_file_thumbnail_share_receiver_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='share',
            name='receiver_email',
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
    ]
