# Generated by Django 4.0.4 on 2022-09-13 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0015_alter_task_task_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stickynote',
            old_name='discription',
            new_name='description',
        ),
    ]
