# Generated by Django 4.0.8 on 2022-11-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0016_rename_discription_stickynote_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails'),
        ),
    ]
