# Generated by Django 4.0.8 on 2022-11-19 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0017_file_thumbnail_blank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestedfield',
            options={'ordering': ['pk']},
        ),
    ]
