# Generated by Django 4.0.8 on 2022-11-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0018_alter_suggestedfield_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='done',
        ),
    ]
