# Generated by Django 4.0.8 on 2022-11-29 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filemanager', '0020_alter_task_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoredSuggestedFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ignored_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignored_suggested_folders', to='filemanager.folder')),
                ('suggested_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_ignored', to='filemanager.suggestedfolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ignored_suggested_folders',
            },
        ),
    ]
