# Generated by Django 4.0.8 on 2022-11-29 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0021_ignoredsuggestedfolder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dismiss_count', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='filemanager.share')),
            ],
            options={
                'db_table': 'share_notifications',
                'ordering': ['-updated_at'],
            },
        ),
    ]
