# Generated by Django 4.0.8 on 2022-11-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0022_sharenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharenotification',
            name='content',
            field=models.JSONField(default=dict),
        ),
    ]
