# Generated by Django 4.0.8 on 2022-12-15 22:24

from django.db import migrations, models
import django.db.models.deletion
import filemanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0023_sharenotification_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to=filemanager.models.upload_video_to)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Processing'), (1, 'Ready')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_files', to='filemanager.folder')),
            ],
            options={
                'db_table': 'video_files',
            },
        ),
    ]
