# Generated by Django 4.0.8 on 2022-12-18 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0027_set_email_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_object_key', models.TextField()),
                ('email_file', models.FileField(upload_to='')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Processing'), (1, 'Processed')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='filemanager.folder')),
            ],
        ),
    ]
