# Generated by Django 4.0.8 on 2022-12-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0031_alter_folderemail_s3_object_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderemail',
            name='sns_message_id',
            field=models.TextField(blank=True),
        ),
    ]
