# Generated by Django 4.0.8 on 2022-12-18 23:18

from django.db import migrations


def forward(apps, schema_editor):
    pass
    # from filemanager.models import Folder
    # for folder in Folder.objects.all():
    #     folder.set_email()


class Migration(migrations.Migration):
    dependencies = [
        ('filemanager', '0032_folderemail_sns_message_id'),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop)
    ]
