# Generated by Django 4.0.8 on 2022-12-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0033_email_format'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FolderEmail',
        ),
    ]
