# Generated by Django 4.0.8 on 2022-12-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0035_folder_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettype',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
