# Generated by Django 4.0.8 on 2023-01-01 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0036_assettype_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_date',
        ),
    ]
