# Generated by Django 4.0.8 on 2023-01-01 04:24

from django.db import migrations, models
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0037_remove_task_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrences',
            field=recurrence.fields.RecurrenceField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
