# Generated by Django 4.0.8 on 2023-01-01 04:25

from django.db import migrations
from django.utils import timezone


def up(apps, schema_editor):
    Task = apps.get_model('filemanager', 'Task')
    for task in Task.objects.all():
        task.start_at = timezone.now()
        task.save()


class Migration(migrations.Migration):
    dependencies = [
        ('filemanager', '0038_task_end_at_task_recurrences_task_start_at'),
    ]

    operations = [
        migrations.RunPython(up, migrations.RunPython.noop)
    ]
