# Generated by Django 4.0.8 on 2023-01-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0039_populate_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
