# Generated by Django 4.0.8 on 2023-01-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0042_taskrepeattracker_task_repeat_tracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='repeat_tracker',
        ),
        migrations.DeleteModel(
            name='TaskRepeatTracker',
        ),
    ]
