# Generated by Django 4.0.8 on 2023-01-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0043_remove_task_repeat_tracker_delete_taskrepeattracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='was_repeated',
            field=models.BooleanField(default=False),
        ),
    ]
