# Generated by Django 4.0.8 on 2023-01-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0044_task_was_repeated'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynote',
            name='short_description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
