# Generated by Django 4.0.8 on 2023-01-16 23:17

import ckeditor.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0045_stickynote_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('short_description', models.CharField(blank=True, editable=False, max_length=150, null=True)),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_notes', to='filemanager.assettype')),
            ],
            options={
                'db_table': 'default_notes',
                'ordering': ['-updated_at'],
            },
        ),
    ]
