# Generated by Django 4.0.10 on 2023-03-08 21:54

from django.db import migrations


def delete_notifications(apps, schema_editor):
    ShareNotification = apps.get_model('filemanager', 'ShareNotification')
    for s in ShareNotification.objects.all():
        if s.dismiss_count >= 2:
            s.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('filemanager', '0047_zippedfolder'),
    ]

    operations = [
        migrations.RunPython(delete_notifications, migrations.RunPython.noop)
    ]
