# Generated by Django 4.0.10 on 2023-03-08 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0048_delete_dismissed_share_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharenotification',
            name='dismiss_count',
        ),
    ]
