# Generated by Django 4.0.10 on 2023-03-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0049_remove_sharenotification_dismiss_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
