# Generated by Django 4.0.10 on 2023-04-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0051_remove_stickynote_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
