# Generated by Django 4.0.10 on 2023-04-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0052_alter_task_start_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
