# Generated by Django 4.0.10 on 2023-06-04 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0053_file_quality_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stickynote',
            name='title',
        ),
    ]
