# Generated by Django 4.0.10 on 2023-06-06 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0054_remove_stickynote_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='start_at',
            new_name='due_at',
        ),
        migrations.CreateModel(
            name='TaskReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to='filemanager.task')),
            ],
            options={
                'db_table': 'task_reminders',
                'ordering': ['-updated_at'],
            },
        ),
    ]
