# Generated by Django 4.0.10 on 2023-06-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0055_rename_start_at_task_due_at_taskreminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reminder_dismissed',
        ),
    ]
