# Generated by Django 4.0.10 on 2023-06-15 09:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('filemanager', '0056_remove_task_reminder_dismissed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('object_id', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'shared_files',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedFileEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shared_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='filemanager.sharedfile')),
            ],
            options={
                'db_table': 'shared_file_emails',
                'ordering': ['-updated_at'],
            },
        ),
    ]
