# Generated by Django 4.0.10 on 2023-06-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0057_sharedfile_sharedfileemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfile',
            name='object_id',
            field=models.TextField(),
        ),
    ]
