# Generated by Django 4.0.10 on 2023-07-01 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filemanager', '0058_alter_sharedfile_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='visibility_reason',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Transferred'), (1, 'Unknown')], default=1),
        ),
        migrations.AddField(
            model_name='folder',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='FolderTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('claimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer', to='filemanager.folder')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferred_folders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
