# Generated by Django 4.0.10 on 2023-07-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0059_folder_visibility_reason_folder_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='disk_usage_bytes',
            field=models.BigIntegerField(default=0),
        ),
    ]
