# Generated by Django 4.0.10 on 2023-07-04 10:17

from django.db import migrations


def get_disk_usage_for_folder(folder) -> int:
    disk_usage = 0
    for file in folder.files.all():
        disk_usage += file.file.size

    for video_file in folder.video_files.all():
        disk_usage += video_file.file.size
    return int(disk_usage)


def up(apps, schema_editor):
    Folder = apps.get_model('filemanager', 'Folder')
    for root_folder in Folder.objects.filter(is_root=True):
        disk_usage = 0
        disk_usage += get_disk_usage_for_folder(root_folder)
        for sub_folder in root_folder.subfolders.all():
            disk_usage += get_disk_usage_for_folder(sub_folder)
        root_folder.disk_usage_bytes = disk_usage
        root_folder.save()


class Migration(migrations.Migration):
    dependencies = [
        ('filemanager', '0060_folder_disk_usage_bytes'),
    ]

    operations = [
        migrations.RunPython(up, migrations.RunPython.noop)
    ]
