# Generated by Django 4.0.10 on 2023-08-07 23:16

from django.db import migrations


def down(apps, schema_editor):
    asset_type_model = apps.get_model("filemanager", "AssetType")
    ai_asset_type = asset_type_model.objects.get(title="AI")
    ai_asset_type.delete()


def up(apps, schema_editor):
    asset_type_model = apps.get_model("filemanager", "AssetType")
    ai_asset_type = asset_type_model(title="AI", hidden=True)
    ai_asset_type.full_clean()
    ai_asset_type.save()


class Migration(migrations.Migration):
    dependencies = [
        ("filemanager", "0061_record_disk_usage"),
    ]

    operations = [migrations.RunPython(up, down)]
