# Generated by Django 4.0.10 on 2023-08-22 19:36

from django.db import migrations


def down(apps, schema_editor):
    folder_model = apps.get_model("filemanager", "Folder")
    root_folders = folder_model.objects.filter(is_root=True)
    for root_folder in root_folders:
        try:
            ai_subfolder = root_folder.subfolders.get(title="AI")
            ai_subfolder.delete()
        except folder_model.DoesNotExist:
            pass


def up(apps, schema_editor):
    folder_model = apps.get_model("filemanager", "Folder")
    root_folders = folder_model.objects.filter(is_root=True)
    for root_folder in root_folders:
        try:
            root_folder.subfolders.get(title="AI")
        except:
            folder_model.objects.create(
                title="AI",
                created_by=root_folder.created_by,
                parent=root_folder,
                is_root=False,
                asset_type=root_folder.asset_type,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("filemanager", "0063_delete_useractivity"),
    ]

    operations = [migrations.RunPython(up, down)]
