# Generated by Django 4.0.10 on 2023-08-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filemanager", "0064_created_default_ai_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="_mime_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
