# Generated by Django 4.0.10 on 2023-08-28 16:10
import tempfile

import magic
from django.db import migrations


def up(apps, schema_editor):
    file_model = apps.get_model("filemanager", "File")
    for file in file_model.objects.all():
        with tempfile.TemporaryFile("wb+") as fp:
            for chunk in file.file.chunks():
                fp.write(chunk)
            fp.seek(0)
            mime = magic.from_buffer(fp.read(), mime=True)
            file._mime_type = mime
            file.save()


class Migration(migrations.Migration):
    dependencies = [
        ("filemanager", "0065_file__mime_type"),
    ]

    operations = [migrations.RunPython(up, migrations.RunPython.noop)]
