# Generated by Django 4.0.8 on 2022-12-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0003_helptopic_order_helptopicimage_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helptopic',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='helptopicimage',
            options={'ordering': ['order']},
        ),
    ]
