# Generated by Django 4.0.8 on 2022-12-27 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djstripe', '0011_2_7'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_link', to='djstripe.plan')),
            ],
            options={
                'db_table': 'payment_links',
            },
        ),
    ]
