# Generated by Django 4.0.8 on 2022-11-21 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filemanager', '0018_alter_suggestedfield_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_address', models.CharField(max_length=255)),
                ('home_type', models.CharField(default='Unknown', max_length=64)),
                ('price_estimate', models.CharField(default='Unknown', max_length=20)),
                ('last_sold_price', models.CharField(default='Unknown', max_length=20)),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lot_size', models.CharField(blank=True, max_length=8)),
                ('living_area', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('no_of_bathrooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number of Bathrooms')),
                ('no_of_full_bathrooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number of Full Bathrooms')),
                ('no_of_half_bathrooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number of Half Bathrooms')),
                ('no_of_quarter_bathrooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number of Quarter Bathrooms')),
                ('no_of_bedrooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number of Bedrooms')),
                ('folder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='filemanager.folder')),
            ],
        ),
    ]
