# Generated by Django 4.0.8 on 2022-12-23 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_home_image_home_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='image',
        ),
    ]
