# Generated by Django 4.0.10 on 2023-05-24 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('requirements', models.JSONField()),
                ('add_photo', models.BooleanField()),
                ('add_video', models.BooleanField()),
                ('add_note', models.BooleanField()),
                ('scan_electrical_panel', models.BooleanField()),
                ('scan_receipt', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sunrun_checklists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sunrun_checklists',
                'ordering': ['-updated_at'],
            },
        ),
    ]
