# Generated by Django 4.0.10 on 2023-05-30 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunrun', '0003_remove_job_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobnote',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='sunrun.job'),
        ),
    ]
