# Generated by Django 4.0.10 on 2023-05-30 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunrun', '0004_alter_jobnote_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobnote',
            name='note',
        ),
    ]
