# Generated by Django 4.0.10 on 2023-05-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunrun', '0005_remove_jobnote_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobnote',
            name='color',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobnote',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
