# Generated by Django 4.0.10 on 2023-05-30 20:06

from django.db import migrations


def delete_all_notes(apps, schema_editor):
    JobNote = apps.get_model('sunrun', 'JobNote')
    JobNote.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('sunrun', '0006_jobnote_color_jobnote_description'),
    ]

    operations = [
        migrations.RunPython(delete_all_notes, migrations.RunPython.noop)
    ]
