# Generated by Django 4.0.10 on 2023-05-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunrun', '0007_delete_all_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobnote',
            name='color',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='jobnote',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
