# Generated by Django 4.0.10 on 2023-05-30 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunrun', '0008_alter_jobnote_color_alter_jobnote_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='electrical_panel_file',
        ),
        migrations.RemoveField(
            model_name='job',
            name='receipt_file',
        ),
    ]
