# Generated by Django 4.0.10 on 2023-05-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunrun', '0009_remove_job_electrical_panel_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='electrical_panel_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='job',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
