# Generated by Django 4.0.10 on 2023-05-30 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sunrun', '0011_remove_job_photos_remove_job_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobphoto',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='sunrun.job'),
        ),
        migrations.AlterField(
            model_name='jobvideo',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='sunrun.job'),
        ),
    ]
