# Generated by Django 4.0.10 on 2023-05-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunrun', '0013_remove_jobphoto_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobphoto',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
