# Generated by Django 4.0.10 on 2023-05-30 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sunrun', '0017_alter_job_receipt_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobvideo',
            name='video',
        ),
    ]
