# Generated by Django 4.0.10 on 2023-06-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunrun', '0021_alter_jobvideo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='checked_requirements',
            field=models.JSONField(default=list),
        ),
    ]
