# Generated by Django 4.0.10 on 2023-06-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunrun', '0022_job_checked_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobphoto',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
