# Generated by Django 4.0.10 on 2023-06-01 23:52

from django.db import migrations, models
import sunrun.models


class Migration(migrations.Migration):

    dependencies = [
        ('sunrun', '0023_alter_jobphoto_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobphoto',
            name='file',
            field=models.FileField(upload_to=sunrun.models.upload_photo_to),
        ),
    ]
