# Generated by Django 4.0.10 on 2023-10-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunrun', '0024_alter_jobphoto_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobnote',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
