# Generated by Django 4.0.4 on 2022-07-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_user_auth_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default.jpg', null=True, ),
        ),
    ]
