# Generated by Django 4.0.4 on 2022-08-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_expires',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
