# Generated by Django 4.0.4 on 2022-08-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0006_remove_user_full_name_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png',
                                    null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
