# Generated by Django 4.0.8 on 2022-11-28 20:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('filemanager', '0020_alter_task_description'),
        ('core', '0009_alter_user_otp'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='IgnoredSuggestedFolder',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('ignored_at', models.DateTimeField(auto_now_add=True)),
        #         ('updated_at', models.DateTimeField(auto_now=True)),
        #         ('suggested_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_ignored', to='filemanager.suggestedfolder')),
        #     ],
        #     options={
        #         'db_table': 'ignored_suggested_folders',
        #     },
        # ),
        # migrations.AddField(
        #     model_name='user',
        #     name='ignored_suggested_folders',
        #     field=models.ManyToManyField(through='core.IgnoredSuggestedFolder', to='filemanager.suggestedfolder'),
        # ),
        # migrations.AddField(
        #     model_name='ignoredsuggestedfolder',
        #     name='user',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
    ]
