# Generated by Django 4.0.8 on 2022-11-29 10:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0010_ignoredsuggestedfolder_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='user',
        #     name='ignored_suggested_folders',
        # ),
    ]
