# Generated by Django 4.0.8 on 2022-11-29 10:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0011_remove_user_ignored_suggested_folders'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='IgnoredSuggestedFolder',
        # ),
    ]
