# Generated by Django 4.0.8 on 2022-12-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_folderremail_folderremailattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderremail',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Processing'), (1, 'Processed')], default=0),
        ),
    ]
