# Generated by Django 4.0.8 on 2022-12-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_folderremail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderremail',
            name='email_message_html',
            field=models.TextField(blank=True),
        ),
    ]
