# Generated by Django 4.0.8 on 2022-12-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_folderremail_email_message_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderremailattachment',
            name='is_image',
            field=models.BooleanField(default=True),
        ),
    ]
