# Generated by Django 4.0.8 on 2022-12-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_folderremailattachment_is_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Folderr Free'), (1, 'Folderr Plus')], default=0),
        ),
    ]
