# Generated by Django 4.0.8 on 2022-12-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receipt_scans',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
