# Generated by Django 4.0.8 on 2022-12-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_user_receipt_scans'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emails_received',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='storage_bytes_used',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
