# Generated by Django 4.0.8 on 2023-01-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_user_emails_received_user_storage_bytes_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_complete',
            field=models.BooleanField(default=True),
        ),
    ]
