# Generated by Django 4.0.8 on 2023-01-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_user_profile_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='random_email',
            field=models.BooleanField(default=False),
        ),
    ]
