# Generated by Django 4.0.8 on 2023-01-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='revenue_cat_app_user_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
