# Generated by Django 4.0.8 on 2023-02-20 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_user_revenue_cat_app_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('secret', models.CharField(max_length=255)),
                ('backup_codes', models.JSONField()),
                ('requested', models.BooleanField(default=False, editable=False)),
                ('active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
