# Generated by Django 4.0.10 on 2023-02-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_sms2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms2fa',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='totp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
