# Generated by Django 4.0.10 on 2023-05-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_email2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Normal'), (1, 'Sunrun Admin'), (2, 'Sunrun Employee')], default=0),
        ),
    ]
