# Generated by Django 4.0.10 on 2023-08-08 19:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS vector;",
                          "DROP EXTENSION vector;")
    ]
