# Generated by Django 4.0.10 on 2023-08-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assetchat", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="For internal use.", max_length=100
                    ),
                ),
                ("content", models.TextField()),
                ("default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
