# Generated by Django 4.0.10 on 2023-08-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assetchat", "0003_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="prompt_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Question Generator"), (1, "Question Answering")],
                default=1,
            ),
        ),
    ]
