# Generated by Django 4.0.10 on 2023-08-22 09:27

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assetchat", "0007_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="temperature",
            field=models.DecimalField(
                decimal_places=1, default=Decimal("0.5"), max_digits=2
            ),
        ),
    ]
